[package]
name = "rolldice"
version = "0.1.2"
license = "GPL-3.0"
authors = ["Michael Aquilina <michaelaquilina@gmail.com>"]
description = "Command line utility to generate dice roll values"

[dependencies]
rand = "0.4"
clap = "2.29"
